### ISSUE TITLE
Can't lower own rank

### ISSUE THREAD

**Issue by MuteTM** [slayer3032/assmod#1]
As the owner, you cannot set your rank lower via the menu. Why not add a check to allow self-demotion to lower ranks?

**Comment by AusHick** [comment]
Owner is consider the "root" privilege.  If you lose that privilege, then it is impossible to restore it short of altering the database, which is not something that should ever need to be done, or supported.

Many other permission systems work off this same premise.

**Comment by MuteTM** [comment]
You can set it via console (how you have to initially set it), no? I can't make sure lower ranks are working correctly if I can't demote myself.

**Comment by slayer3032** [comment]
Server Owner is exempt from promotion/demotion by design and it's intended only for people who are literally server owners and have access to the server files. I wouldn't really suggest making a command purely for demoting server owners. Otherwise the only other way to auth the command would be to allow anything with server owner permissions to run it. if you're just testing out ranks my suggestion would be to delete your ranking file which is your SteamID64 from data/assmod/users and rejoin.
